datawire/go-mkopensource

pkg/detectlicense/licenses.go
The package github.com/josharian/intern (implicitly required by more
recent versions of `k8s.io/kube-openapi`) has an undetected MIT-license.
This commit adds a special case for it.
=> Detect lowercase licence.md in github.com/josharian/intern. 

exitcodes.go, main.go, pkg/dependencies/dependencyinfo.go, pkg/dependencies/dependencyinfo_test.go, pkg/detectlicense/licenses.go
Some code for validating licenses and generating some of the license information JSON body was duplicated in `py-mkopensource` and `js-mkopensource`
This PR consolidates all those changes here so we only keep language-specific parsing logic in the other applications.
This change also contains a fix for incorrect license detection for telepresence
=> Generate license URLs in one place so it can be reused by other applications.

README.md, dependency.go, dependency_test.go, main.go, pkg/dependencies/dependencyinfo.go, pkg/dependencies/dependencyinfo_test.go, pkg/detectlicense/licenses.go
This PR implements validations based on this [document](https://www.notion.so/datawire/License-Management-5194ca50c9684ff4b301143806c92157)
There is a command line option `--application-type` that can be:
`external`: For applications that run on customer servers
`internal`: For applications that run on Ambassador servers
This flag control what validation is applied when checking licenses.
License validation code has been implemented as a package that can be reused in other applications.
=> Allow checking if dependencies of an application use a forbidden license

pkg/detectlicense/licenses.go
go-mkopensource has issues detecting licenses for `github.com/datawire/saas_app` and `github.com/datawire/telepresence-pro` because there are no LICENSE* files
These apps are proprietary so they have been marked as such, which will prevent issues when packages in these apps are used in other projects.
=> Mark github.com/datawire/saas_app and github.com/datawire/telepresence-pro as proprietary

build-aux/docker/customLicenseFormat.json, cmd/go-mkopensource/main.go, cmd/go-mkopensource/main_test.go, cmd/go-mkopensource/testdata/07-forbidden-license/agpl/agpl.go, cmd/go-mkopensource/testdata/07-forbidden-license/agpl/go.mod, cmd/go-mkopensource/testdata/07-forbidden-license/expected_err.txt, cmd/go-mkopensource/testdata/07-forbidden-license/go.mod, cmd/go-mkopensource/testdata/07-forbidden-license/go.sum, cmd/go-mkopensource/testdata/07-forbidden-license/main.go, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/expected_err.txt, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/go.mod, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/go.sum, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/gpl/go.mod, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/gpl/gpl.go, cmd/go-mkopensource/testdata/08-allowed-for-internal-use-only/main.go, cmd/js-mkopensource/dependency/dependency.go, cmd/js-mkopensource/dependency/hardcodeddependencies.go, cmd/py-mkopensource/testdata/successful-generation/expected_json.json, pkg/dependencies/dependencyinfo.go, pkg/detectlicense/licenses.go, pkg/detectlicense/validationexceptions.go
While scanning Ambassador Cloud, several libraries used licenses that were not recognized by the application.
Changes:
1. Added support in `go-mkopensource` to hard-code some dependencies that are difficult to recognize
2. Added additional JS hard-coded libraries that are difficult to identify
3. Added additional license types the the `detectlicense` and `dependencies` packages
=> Add new license types

README.md, build-aux/docker/go_builder.dockerfile, build-aux/docker/js_builder.dockerfile, build-aux/docker/py_builder.dockerfile, build-aux/docker/scan-go.sh, build-aux/docker/scan-js.sh, build-aux/generate.sh, pkg/detectlicense/validationexceptions.go
Ambassador Cloud build was failing because the GitHub build container was using an old version of Go  (1.15) and `go-mkopensource` uses features from `1.16`. This PR changes how binaries are build to address this problem.
There is also a change in the main script used when generating dependencies to user `/bin/bash` instead of `/bin/env bash` since some developer machines don't have the `/bin/env` binary.
=> Fixes required to fix issues in Ambassador Cloud build

cmd/py-mkopensource/main.go, cmd/py-mkopensource/main_test.go, cmd/py-mkopensource/testdata/agpl-license/expected_err.txt, cmd/py-mkopensource/testdata/gpl-license/expected_err.txt, cmd/py-mkopensource/testdata/unknown-license/dependency_list.txt, cmd/py-mkopensource/testdata/unknown-license/expected_err.txt, pkg/dependencies/dependencyinfo.go, pkg/dependencies/dependencyinfo_test.go
Python scanner was not using the same logic as Go scanner when an error was found, which made it difficult to figure out what was happening.
This PR makes bot CLI tools consistent, so all Python errors are identified and printed, instead of printing one error at a time.
=> Better error handling in Python scanner

cmd/js-mkopensource/dependency/dependency.go, cmd/js-mkopensource/dependency/dependency_test.go, cmd/js-mkopensource/dependency/hardcodeddependencies.go, cmd/js-mkopensource/dependency/testdata/empty-license/dependencies.json, cmd/js-mkopensource/dependency/testdata/empty-license/expected_err.txt, cmd/js-mkopensource/dependency/testdata/license-field-as-an-array/dependencies.json, cmd/js-mkopensource/dependency/testdata/license-field-as-an-array/expected_output.json, pkg/detectlicense/licenses.go
License scanner for NPM sometimes outputs licenses as a string and sometimes as a list
String sample
```
"licenses": "MIT"
```
List sample
```
"licenses": [
"AFLv2.1",
"CC-BY-3.0"
]
```
List format was not supported and this PR adds support for it.
In addition, NPM library `json-schema@0.2.3` has a license that's difficult to parse and it was hard-coded.
=> Support NPM depencency json to have licenses as string or as list

build-aux/docker/scan-js.sh
**What**
Install npm dependencies using the `-f` (Force) option, so that platform-specific dependencies are installed.
**Why**
GitHub checks are failing for some people in the Cloud team because they use macOs and GitHub check runs on Linux.
Due to this, check will fail indicating that file `DEPENDENCIES.md` is out-of-date.
See [this](https://github.com/datawire/saas_app/runs/5294070577?check_suite_focus=true) failure for an example of this issue.
**Tests**
Ran Node.Js dependency script on a Linux machine and verified that macOs, Windows, etc. dependencies are included in `DEPENDENCIES.md` file
**Risks**
It seems like `npm install` will just download all dependencies. It doesn't try to compile or run any code, so installation works on any system. For example, fsevents is a macOs only …
=> Include platform-specific dependencies in DEPENDENCIES.md file for Node.Js

README.md, cmd/go-mkopensource/main.go, pkg/detectlicense/package_licenses_file.go, pkg/detectlicense/package_licenses_file_test.go
Some components cannot be parsed by this license checker and this
creates a churn when upgrading component versions, making such upgrades
dependent on new versions of this checker. Typical scenario
1. We want to release a new version of component x.
2. The new release must use the latest of component y.
3. The go-mkopensource refuses to parse something that the y points to.
4. Our release is blocked on a new mk-opensource release.
This addition removes the block by making it possible for component x
to specify the SPDX licenses that component y is using.
Closes #8
=> Add an escape-hatch yaml file that maps packages to SPDX licenses

pkg/detectlicense/licenses.go, pkg/detectlicense/testdata/Apache2+MIT/eca2fcce94de90a652b7924ef1ce971a9e0fe327
The `gvisor.dev/gvisor/LICENSE` file found in https://github.com/google/gvisor/blob/master/LICENSE is a valid Apache 2.0 license and a MIT license after a dashed line.
=> Recognize gvisor's Apache 2.0 + MIT license

README.md, cmd/go-mkopensource/modules_txt.go
Prior to this PR, the scanner didn't install the dependencies required by the `go mod vendor` command. With this PR, the scanner can install the dependencies and continue the scanning in the project. 
In order to test this PR, I use the master branch from saas_app on my local machine and update the [Makefile](https://github.com/datawire/saas_app/blob/33c1786904a5c0100d538d6d85ef632c47a1851a/Makefile#L754) to point to the latest commit in this PR.
=> install dependencies with the scanner

cmd/go-mkopensource/modules_txt.go
Prior to this PR, if the go mod vendor command doesn't ask to install a dependency the scanner loops without finishing the process.
Now if the scanner doesn't find a dependency to install, it will fail in order to stop the process and ask for human intervention.
To test this PR checkout the master branch of saas_app, then go to the `go.sum` file in saas_app and delete any entry on it. Switch the `MKOPENSOURCE_COMMIT` in the `Makefile` for the commit on this PR. The scanner should fail. Also, the output from the `go mod vendor` command is displayed for a better understanding of the problem
=> Return an error if there is none depency to install

.github/workflows/test-action.yml, DEPENDENCIES.md, DEPENDENCY_LICENSES.md, README.md, actions/save-dependabot-changes/action.yml, actions/save-dependabot-changes/commit.sh, actions/save-dependabot-changes/is_dirty.sh
Some workflows are calling action `save-dependabot-changes` on push, which could trigger an update of `master` after a merge.
This is not a problem if the user doing the merge is not dependabot, but since it's possible to enable auto-merge of dependabot PRs, this could be a problem.
This PR makes the following changes:
1. Add a new input argument `branches_to_skip` to the action
2. Improve logging, so it's easier to understand what's being done
3. Add tests to verify that the action behaves as expected.
=> Update action `save-dependabot-changes` to enable skipping changes made to some branches

.github/workflows/test-action.yml, DEPENDENCY_LICENSES.md, README.md, actions/save-dependabot-changes/action.yml
Previously, the action required a PAT with `repo:write` privileges.
This change removed that requirement, improving security.
This token was required because commits made with the GITHUB_TOKEN do not trigger a workflow re-run. This was solved by re-running the workflow using the gh cli.
=> Update action `save-dependabot-changes` to it does not need a privileged user to run

.github/workflows/test-action.yml, DEPENDENCY_LICENSES.md, actions/save-dependabot-changes/action.yml, actions/save-dependabot-changes/commit.sh
This will prevent polluting the branch where a developer is testing changes to the action.
Tests:
Verified that the tests didn't make any commit.
=> Updated action tests so they won't push changes during testing

.github/workflows/test-action.yml, build-aux/docker/go_builder.dockerfile, build-aux/generate.sh
go-mkopensource will update dependencies as necessary when `go mod vendor` fails, which will change go.mod and go.sum.
When dependency scanning finishes, the modified do.mod/go.sum should also be returned back to the application so they can be commited.
The impact of this issue is that the dependency files will show dependencies that do not match what's in go.mod.
Tested from saas_app. This [workflow](https://github.com/datawire/saas_app/actions/runs/4164305580/jobs/7205771757) saves DEPENDENCIES.md as well as go.mod and go.sum.
=> Fix go.mod not being copied from the docker image back to the application repo

cmd/go-mkopensource/main.go, cmd/js-mkopensource/dependency/hardcodeddependencies.go, pkg/detectlicense/licenses.go, pkg/detectlicense/proprietary.go, pkg/detectlicense/proprietary_test.go, pkg/detectlicense/testdata/proprietary_software.yaml, pkg/detectlicense/validationexceptions.go
add an additional flag `--proprietary-software` that points to a YAML file containing proprietary go packages:
```
- github/datawire/foo
- github/datawire/bar
```
=> make proprietary packages configurable

build-aux/generate.sh
The dependency generation script was not excluding the NPM test data files during dependency generation, which could add unwanted dependencies to the dependency files.
The script was updated to remove test data files before it runs.
=> Delete test data files before NPM dependencies are scanned

.github/workflows/test-action.yml, README.md, build-aux/docker/go_builder.dockerfile, build-aux/docker/scan-go.sh, build-aux/generate.sh, cmd/go-mkopensource/testdata/00-intern-old/expected_err.txt, cmd/go-mkopensource/testdata/03-multierror/expected_err.txt, cmd/js-mkopensource/dependency/testdata/empty-license/expected_err.txt, cmd/js-mkopensource/dependency/testdata/hardcoded-dependencies-but-different-version/expected_err.txt, cmd/js-mkopensource/dependency/testdata/missing-license/expected_err.txt, cmd/js-mkopensource/dependency/testdata/unknown-license/expected_err.txt, cmd/py-mkopensource/testdata/unknown-license/expected_err.txt, pkg/scanningerrors/explain.go
Add a command line option to the generate script that can be used to pass a list of proprietary licenses that will not be added to the generated output.
There was also a bug in the generate.sh script and it was aborting generation before any change was done. This has been fixed in 0474f48075f08693c489ae94cb4162c51a7a5a38.
=> Allow passing a list of proprietary dependencies

build-aux/docker/go_builder.dockerfile
- Updated image used to generate go license information to use go 1.20
- Fix regex that gets the Go version to allow version numbers containing a 0 e.g. 1.2**0**
=> Update go builder to support go 1.20

.github/workflows/test-action.yml
The CI smoke test has been failing when run against the `master` branch (or any branch matching `master` technically), as the logic is currently set to `branches_to_skip: master`, but the subsequent check does not take this into account.
We can make this verification more complex in the future to handle more use-cases, but for now, the coverage is reasonable here.
=> Do not fail CI for appropriately skipped branch
